name: CI

on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Especifique a versão do Python que deseja utilizar
    
    - name: Install dependencies requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install pytest-cov
        pip install codecov

    - name: Set up Codecov token
      run: |
        echo "export CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}" >> $GITHUB_ENV
      
    - name: Run Flake8
      run: |
        flake8

    - name: Run Pytest with coverage
      run: |
        pytest --cov .
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        slug: lfstos/libpythonpro
                
    - name: Upload coverage reports to Codecov (after success)
      if: success()
      run: |
        codecov